---
title: Python para Datos
subtitle: Primeros pasos para an치lisis y visualizaci칩n
date: last-modified
author:
  - name: Francisco Palm
    orcid: 0000-0002-1293-0868
    email: fpalm@qu4nt.com
    affiliations: qu4nt, activistasxsl
format:
  clean-revealjs
html-math-method:
  method: mathjax
  url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
lang: es
logo: images/qu4nt-logo.png
---

# Introducci칩n a Datos Tabulares y Gr치ficas en Python

## Agenda

\

1. Lectura de datos tabulares con Pandas  
2. Exploraci칩n y selecci칩n de datos con DataFrames  
3. Visualizaci칩n de datos con Matplotlib y Pandas

# 1. Lectura de Datos Tabulares

## Pandas y DataFrames

\

- [Pandas](https://pandas.pydata.org/) es la biblioteca m치s usada para datos tabulares en Python.  
- Similar a las tablas de R.  
- Un **DataFrame** es una tabla con filas y columnas. 
  - Cada columna puede ser de un tipo diferente.
  - Cada fila puede ser de un tipo diferente.
  - Las columnas y las filas tienen 칤ndices. 


## Cargando un archivo CSV

\

```{python}
#| echo: true

import pandas as pd

data_oceania = pd.read_csv("../data/gapminder_gdp_oceania.csv")
print(data_oceania)
```

---

## Usando una columna como 칤ndice

\

```{python}
#| echo: true
data_oceania_country = pd.read_csv(
    "../data/gapminder_gdp_oceania.csv",
    index_col="country"
)
print(data_oceania_country)
```

---

## Inspeccionando un DataFrame

\

```{python}
#| echo: true
data_oceania_country.info()
data_oceania_country.columns
```

---

## Transponer y describir datos

\

```{python}
#| echo: true
print(data_oceania_country.T)
print(data_oceania_country.describe())
```

---

## Ejercicio 游눠

* Lee `gapminder_gdp_americas.csv` en un DataFrame.
* Usa `.describe()` para ver sus estad칤sticas.

# 2. Exploraci칩n de DataFrames

## Selecci칩n por posici칩n e 칤ndice

\

```{python}
#| echo: true
data = pd.read_csv("../data/gapminder_gdp_europe.csv", index_col="country")

# Por posici칩n
print(data.iloc[0, 0])

# Por etiqueta
print(data.loc["Albania", "gdpPercap_1952"])
```

## Slices y subconjuntos

\

```{python}
#| echo: true
# Todas las columnas para Albania
print(data.loc["Albania", :])

# Varias filas y columnas
print(data.loc["Italy":"Poland", "gdpPercap_1962":"gdpPercap_1972"])
```

## Operaciones sobre subconjuntos

\

```{python}
#| echo: true
subset = data.loc["Italy":"Poland", "gdpPercap_1962":"gdpPercap_1972"]
print(subset.max())
print(subset.min())
```

## Filtros con m치scaras booleanas

\

```{python}
#| echo: true
mask = subset > 10000
print(subset[mask])
```

## Agrupamiento (split-apply-combine)

\

```{python}
#| echo: true
mask_higher = data > data.mean()
wealth_score = mask_higher.aggregate("sum", axis=1) / len(data.columns)

print(data.groupby(wealth_score).sum())
```

## Ejercicio 游눠

\

* Encuentra el PIB per c치pita de Serbia en 2007.
* Selecciona los pa칤ses con PIB > 10000 en 1972.


# 3. Visualizaci칩n de Datos


## matplotlib y pyplot

```{python}
#| echo: true
import matplotlib.pyplot as plt

time = [0, 1, 2, 3]
position = [0, 100, 200, 300]

plt.plot(time, position)
plt.xlabel("Time (hr)")
plt.ylabel("Position (km)")
plt.show()
```

## Graficando desde un DataFrame

```{python}
#| echo: true
data = pd.read_csv("../data/gapminder_gdp_oceania.csv", index_col="country")

years = data.columns.str.replace("gdpPercap_", "").astype(int)
data.columns = years

data.loc["Australia"].plot()
```

## Varias series en un mismo gr치fico

```{python}
#| echo: true
data.T.plot()
plt.ylabel("GDP per capita")
```

## Personalizaci칩n y estilos

```{python}
#| echo: true
plt.style.use("ggplot")
data.T.plot(kind="bar")
plt.ylabel("GDP per capita")
```

## Leyendas y formatos

```{python}
#| echo: true
plt.plot(years, data.loc["Australia"], "b-", label="Australia")
plt.plot(years, data.loc["New Zealand"], "g-", label="New Zealand")
plt.legend(loc="upper left")
```

## Scatter plots

```{python}
#| echo: true
plt.scatter(data.loc["Australia"], data.loc["New Zealand"])
```

## Guardando gr치ficos

\

```{python}
#| echo: true
plt.scatter(data.loc["Australia"], data.loc["New Zealand"])
plt.savefig("mi_grafico.png")
```

## Ejercicio 游눠

\

* Grafica el m칤nimo y m치ximo PIB per c치pita de Europa en cada a침o.
* Crea un scatter plot PIB vs esperanza de vida (2007).

## 춰Gracias\!

\

**쯇reguntas?**

